ProcessAuto/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProcessAuto.Areas.Identity.Data;
using ProcessAuto.Data;
using ProcessAuto.Models;
using ProcessAuto.Models.Enums;
using ProcessAuto.Models.ViewModels;

namespace ProcessAuto.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<PAUser> _userManager;
        private readonly SignInManager<PAUser> _signInManager;

        public CompaniesController(ApplicationDbContext context, UserManager<PAUser> userManager, SignInManager<PAUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            var email = User.Identity.Name;
            var currentUser = await _context.Users.FirstOrDefaultAsync(x => x.Email == email);
            if (currentUser.Company != null)
            {
                ViewBag.User = ((CompanyNames)currentUser.Company).ToString();
            }

            

            return View(await _context.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CompaniesViewModel model)
        {
            var id = _context.Companies.Any() ? _context.Companies.Max(x => x.Id) : 0;
            if (ModelState.IsValid)
            {

                var company = new Company
                {
                    Id = id + 1,
                    Name = ((CompanyNames)id + 1).ToString(),
                };

                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Info,LinkToWebsite")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.FindAsync(id);
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

ProcessAuto/Controllers/HRRegistrationController.cs
using ExcelDataReader;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProcessAuto.Areas.Identity.Data;
using ProcessAuto.Models;
using ProcessAuto.Models.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace ProcessAuto.Controllers
{
    public class HRRegistrationController : Controller
    {
        private readonly UserManager<PAUser> _userManager;
        private readonly SignInManager<PAUser> _signInManager;
        List<HumanResources> HR = new List<HumanResources>();

        public HRRegistrationController(UserManager<PAUser> userManager, SignInManager<PAUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }


        // GET: StudentsRegistrationController
        [HttpGet]
        public ActionResult Index()
        {
            return View(new List<HumanResources>());
        }

        [HttpPost]
        public async Task<IActionResult> IndexAsync(IFormCollection form)
        {

            var fileName = "./Companies.xlsx";
            // For .net core, the next line requires the NuGet package, 
            // System.Text.Encoding.CodePages
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            using (var stream = System.IO.File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {

                    while (reader.Read()) //Each row of the file
                    {
                        HR.Add(new HumanResources
                        {
                            Surname = reader.GetValue(0).ToString(),
                            Name = reader.GetValue(1).ToString(),                          
                            MiddleName = reader.GetValue(2).ToString(),
                            Email = reader.GetValue(3).ToString(),
                            Password = "123456qW!",
                            Company = Int32.Parse(reader.GetValue(4).ToString())
                            
                        });
                    }
                }
            }

            foreach (var hr in HR)
            {
                var user = new PAUser { UserName = hr.Email, 
                                        Email = hr.Email,                                         
                                        EmailConfirmed = true, 
                                        Company = hr.Company,
                                        Name = hr.Name,
                                        Surname = hr.Surname,
                                        MiddleName = hr.MiddleName};

                var result = await _userManager.CreateAsync(user, hr.Password);
                if(result.Succeeded)
                {
                    IdentityResult roleresult = await _userManager.AddToRoleAsync(user, "COMPANY");
                }
            }
            return View(HR);
        }
    }
}

ProcessAuto/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using ProcessAuto.Data;
using ProcessAuto.Models.ViewModels;
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using ProcessAuto.Models;

namespace ProcessAuto.Controllers
{
    public class ResumeController : Controller
    {

        private readonly ApplicationDbContext _context;

        //UserManager<IdentityUser> _userManager;

        public ResumeController(ApplicationDbContext context)
        {
            _context = context;
            //_userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //var student = await this._context.Users.SingleOrDefaultAsync(x => x.Id == studentId);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            var email = User.Identity.Name;
            if (currentUserResume == default)
            {
                CreateResumeInDB(email);
                currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            }
            if (currentUserResume != default)
            {
                ResumeViewModel model = new ResumeViewModel
                {
                    AboutYourself = currentUserResume.AboutYourself,
                    Stack = currentUserResume.Stack,
                    Hobbies = currentUserResume.Hobbies,
                    WorkingExperience = currentUserResume.WorkingExperience,
                    ProgrammingLanguages = currentUserResume.ProgrammingLanguages
                };
                return View(model);
            }
            else return NotFound("Not Found");
        }

        public async Task CreateResumeInDB(string email)
        {
            var curUser = await _context.Users.FirstOrDefaultAsync(x => x.Email == email);
            //var id = curUser.Id;
            _context.Resumes.Add(new Resume
            {
                student = curUser,
                Stack = "no stack",
                ProgrammingLanguages = "no langs",
                WorkingExperience = "no xp",
                AboutYourself = "student",
                Hobbies = "no hobbies",
            });
            await _context.SaveChangesAsync();
            return;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                var model = new ResumeViewModel
                {
                    AboutYourself = currentUserResume.AboutYourself,
                    Stack = currentUserResume.Stack,
                    Hobbies = currentUserResume.Hobbies,
                    WorkingExperience = currentUserResume.WorkingExperience,
                    ProgrammingLanguages = currentUserResume.ProgrammingLanguages
                };
                return View(model);
            }
            else return StatusCode(404, "NotFound");
            /*var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                currentUserResume.WorkingExperience = "kek";
                currentUserResume.ProgrammingLanguages = "kek";
                currentUserResume.Hobbies = "kek";
                currentUserResume.Stack = "kek";
                currentUserResume.AboutYourself = "kek";
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else return StatusCode(404, "Not found");*/
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(ResumeViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                currentUserResume.WorkingExperience = model.WorkingExperience;
                currentUserResume.ProgrammingLanguages = model.ProgrammingLanguages;
                currentUserResume.Hobbies = model.Hobbies;
                currentUserResume.Stack = model.Stack;
                currentUserResume.AboutYourself = model.AboutYourself;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else return StatusCode(404, "Not found");
        }
    }
}

ProcessAuto/Controllers/RolesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using ProcessAuto.Models;
using ProcessAuto.Models.ViewModels;
using ProcessAuto.Areas.Identity.Data;

namespace ProcessAuto.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<PAUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<PAUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            PAUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            PAUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

ProcessAuto/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ProcessAuto.Areas.Identity.Data
@inject SignInManager<PAUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HITSI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a style="text-align: center" class="navbar-brand" href="#">
                    <img style="border-radius: 50px" src="https://psv4.vkuseraudio.net/s/v1/d/M5cWHB32995m9rHNNe8aRJ-sNlH5n8u3aVBe-kefmab103KTtcE6jz7eO1Cmh2DJ7K7m4abvfJL65HNc6vrEF4ZKiCM4bfZrGzuBUW2bvgDHmkNpMo1tqA/draw_svg20200612-15006-iogc5s_svg.png" alt="" width="45" height="45" class="m-1  align-text-center">HITSI
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (User.IsInRole("Deanery"))
                        {
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                AddUsers
                              </a>
                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="HRRegistration" asp-action="Index">HR's</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="StudentsRegistration" asp-action="Index">Students</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                              </ul>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Deanery") || User.IsInRole("Admin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Deanery" asp-action="ShowAllStudents">Students</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Company"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vacancies" asp-action="ShowCompaniesVacancies">My vacancies</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Resume" asp-action="Index">Resume</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vacancies" asp-action="Index">Vacancies</a>
                            </li>
                        }

                        @if(User.IsInRole("Admin")){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        } 
                        
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VacancyResponds" asp-action="ShowSelfResponds">My Responds</a>
                            </li>
                        }        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProcessAuto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>