ProcessAuto/Models/Vacancy.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ProcessAuto.Models
{
    public class Vacancy
    {

        [Key]
        public int Id { get; set; }        

        public string Company { get; set; }
        public int CompanyId { get; set; }
        public string Position { get; set; }        
        public string Stack { get; set; }
        public string Slots { get; set; }                      
    }
   
}

ProcessAuto/Models/ViewModels/VacancyViewModel.cs
namespace ProcessAuto.Models.ViewModels
{
    public class VacancyViewModel
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public int CompanyId { get; set; }
        public string Position { get; set; }
        public string Stack { get; set; }
        public string Slots { get; set; }
    }
}

ProcessAuto/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using ProcessAuto.Data;
using ProcessAuto.Models.ViewModels;
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using ProcessAuto.Models;

namespace ProcessAuto.Controllers
{
    public class ResumeController : Controller
    {

        private readonly ApplicationDbContext _context;

        //UserManager<IdentityUser> _userManager;

        public ResumeController(ApplicationDbContext context)
        {
            _context = context;
            //_userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //var student = await this._context.Users.SingleOrDefaultAsync(x => x.Id == studentId);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            var email = User.Identity.Name;
            if (currentUserResume == default)
            {
                CreateResumeInDB(email);
                currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            }
            if (currentUserResume != default)
            {
                ResumeViewModel model = new ResumeViewModel
                {
                    AboutYourself = currentUserResume.AboutYourself,
                    Stack = currentUserResume.Stack,
                    Hobbies = currentUserResume.Hobbies,
                    WorkingExperience = currentUserResume.WorkingExperience,
                    ProgrammingLanguages = currentUserResume.ProgrammingLanguages
                };
                return View(model);
            }
            else return NotFound("Not Found");
        }

        public async Task CreateResumeInDB(string email)
        {
            var curUser = await _context.Users.FirstOrDefaultAsync(x => x.Email == email);
            //var id = curUser.Id;
            _context.Resumes.Add(new Resume
            {
                student = curUser,
                Stack = "no stack",
                ProgrammingLanguages = "no langs",
                WorkingExperience = "no xp",
                AboutYourself = "student",
                Hobbies = "no hobbies",
            });
            await _context.SaveChangesAsync();
            return;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                var model = new ResumeViewModel
                {
                    AboutYourself = currentUserResume.AboutYourself,
                    Stack = currentUserResume.Stack,
                    Hobbies = currentUserResume.Hobbies,
                    WorkingExperience = currentUserResume.WorkingExperience,
                    ProgrammingLanguages = currentUserResume.ProgrammingLanguages
                };
                return View(model);
            }
            else return StatusCode(404, "NotFound");
            /*var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                currentUserResume.WorkingExperience = "kek";
                currentUserResume.ProgrammingLanguages = "kek";
                currentUserResume.Hobbies = "kek";
                currentUserResume.Stack = "kek";
                currentUserResume.AboutYourself = "kek";
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else return StatusCode(404, "Not found");*/
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(ResumeViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUserResume = await _context.Resumes.FirstOrDefaultAsync(x => x.student.Id == userId);
            if (currentUserResume != default)
            {
                currentUserResume.WorkingExperience = model.WorkingExperience;
                currentUserResume.ProgrammingLanguages = model.ProgrammingLanguages;
                currentUserResume.Hobbies = model.Hobbies;
                currentUserResume.Stack = model.Stack;
                currentUserResume.AboutYourself = model.AboutYourself;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else return StatusCode(404, "Not found");
        }
    }
}

ProcessAuto/Controllers/VacancyRespondsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProcessAuto.Data;
using System;
using System.Threading.Tasks;
using ProcessAuto.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using System.Security.Claims;
using System.Collections.Generic;

namespace ProcessAuto.Controllers
{
    public class VacancyRespondsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VacancyRespondsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("VacancyResponds/AssignInterview/{respondId}")]
        public async Task<IActionResult> AssignInterview(int respondId, int vacId)
        {
            var model = new AssignInverviewViewModel { respondId = respondId };
            model.vacId = vacId;
            return View(model);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AssignInterview(AssignInverviewViewModel model)
        {
            var respond = await _context.Responds.FirstOrDefaultAsync(x => x.Id == model.respondId);

            if (respond == null)
                return NotFound("No such respond");

            var dateArray = model.InterviewDate.ToCharArray();
            var newDateArray = model.InterviewDate.ToCharArray();
            newDateArray[0] = dateArray[3];
            newDateArray[1] = dateArray[4];
            newDateArray[3] = dateArray[0];
            newDateArray[4] = dateArray[1];
            var newDate = new string(newDateArray);
            respond.InterviewDate = Convert.ToDateTime(newDate);

            respond.VacancyStage = Models.VacancyStage.InterviewAssigned;
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowVacancyResponds", "Vacancies", new { vacId = model.vacId});
        }

        [HttpGet]
        [Route("VacancyResponds/SetStatusNoOffer/{respondId}")]
        public async Task<IActionResult> SetStatusNoOffer(int respondId, int vacId)
        {
            var model = new AssignInverviewViewModel { respondId = respondId };
            model.vacId = vacId;
            return View(model);
        }

        [HttpPost]        
        [Authorize]
        public async Task<IActionResult> SetStatusNoOffer(AssignInverviewViewModel model)
        {
            var respond = await _context.Responds.FirstOrDefaultAsync(x => x.Id == model.respondId);

            if (respond == null)
                return NotFound("No such respond");

            respond.VacancyStage = Models.VacancyStage.NoOffer;
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowVacancyResponds", "Vacancies", new { vacId = model.vacId });
        }

        [HttpGet]
        [Route("VacancyResponds/SetStatusOfferSent/{respondId}")]
        public async Task<IActionResult> SetStatusOfferSent(int respondId, int vacId)
        {
            var model = new AssignInverviewViewModel { respondId = respondId };
            model.vacId = vacId;
            return View(model);
        }

        [HttpPost]      
        [Authorize]
        public async Task<IActionResult> SetStatusOfferSent(AssignInverviewViewModel model)
        {
            var respond = await _context.Responds.FirstOrDefaultAsync(x => x.Id == model.respondId);

            if (respond == null)
                return NotFound("No such respond");

            respond.VacancyStage = Models.VacancyStage.OfferSent;
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowVacancyResponds", "Vacancies", new { vacId = model.vacId });
        }

        public async Task<IActionResult> ShowSelfResponds ()
        {
            var currentStudentId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return await ShowStudentsResponds(currentStudentId);            
        }

        public async Task<IActionResult> ShowStudentsResponds (string studentId)
        {
            var currentStudent = await _context.Users.FirstOrDefaultAsync(x => x.Id == studentId);
            var responds = _context.Responds.Where(x => x.student == currentStudent).Include(y => y.vacancy);

            List<VacancyRespondViewModel> respondsDTO = new List<VacancyRespondViewModel>();

            foreach (var r in responds)
            {
                var currentVacancy = r.vacancy;

                respondsDTO.Add(new VacancyRespondViewModel
                {
                    Company = currentVacancy.Company,
                    VacancyStack = currentVacancy.Stack,
                    Slots = currentVacancy.Slots,
                    Position = currentVacancy.Position,                    

                    RespondId = r.Id,
                    VacancyId = currentVacancy.Id,

                    RespondStage = r.VacancyStage,
                    StudentsVerdict = r.StudentsVerdict,

                    InterviewDate = r.InterviewDate
                });
            }

            this.ViewData["Responds"] = respondsDTO;            

            return View();
        }

        [HttpGet]
        [Route("VacancyResponds/AcceptOffer/{respondId}")]
        public async Task<IActionResult> AcceptOffer (int respondId, int vacId)
        {
            var model = new AssignInverviewViewModel { respondId = respondId };
            model.vacId = vacId;
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AcceptOffer (AssignInverviewViewModel model)
        {
            var respond = await _context.Responds.FirstOrDefaultAsync(x => x.Id == model.respondId);

            if (respond == null)
                return NotFound("No such respond");
            
            respond.StudentsVerdict = Models.StudentsVerdict.Accepted;
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowSelfResponds", new { });
        }

        [HttpGet]
        [Route("VacancyResponds/DeclineOffer/{respondId}")]
        public async Task<IActionResult> DeclineOffer (int respondId, int vacId)
        {
            var model = new AssignInverviewViewModel { respondId = respondId };
            model.vacId = vacId;
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeclineOffer (AssignInverviewViewModel model)
        {
            var respond = await _context.Responds.FirstOrDefaultAsync(x => x.Id == model.respondId);

            if (respond == null)
                return NotFound("No such respond");

            respond.StudentsVerdict = Models.StudentsVerdict.Declined;
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowSelfResponds", new { });
        }
    }
}

ProcessAuto/Views/Vacancies/Create.cshtml
@model ProcessAuto.Models.ViewModels.VacancyViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Stack" class="control-label"></label>
                <input asp-for="Stack" class="form-control" />
                <span asp-validation-for="Stack" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slots" class="control-label"></label>
                <input asp-for="Slots" class="form-control" />
                <span asp-validation-for="Slots" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Slots" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProcessAuto/Views/Vacancies/Index.cshtml
@using ProcessAuto.Models.ViewModels
@using System.Collections
@model ProcessAuto.Models.ViewModels.VacancyViewModel

@{
    ViewData["Title"] = "Vacancies";
}
@*<h1>@ViewData["Title"]</h1>

<p>This page will be avaliable for logged user and will let them edit their resume.</p>*@

<h4>@ViewData["Title"]</h4>
@if (User.IsInRole("Company"))
{
    <a class="btn btn-btn-outline-success" asp-area="" asp-controller="Vacancies" asp-action="Create">Create</a>
}
@{
    IEnumerable<VacancyViewModel> vacancies = ViewData["Vacancies"] as IEnumerable<VacancyViewModel>; 
}

<div class="list-group">

@foreach (VacancyViewModel vacancy in vacancies)
{
 
  <a href="Vacancies/@vacancy.Id" class="list-group-item list-group-item-action flex-column align-items-start">    
    <p class="mb-1">Company: @vacancy.Company</p>    
    <p class="mb-1">Stack: @vacancy.Stack</p>   
    <p class="mb-1">Position: @vacancy.Position</p>   
    <p class="mb-1">Slots: @vacancy.Slots</p>       
  </a>

}    

</div>

@*<a class="btn btn-outline-danger" asp-area="" asp-controller="Vacancies" asp-action="Edit">Roles</a>*@

@*@using(Html.BeginForm("Buy", "Resume", FormMethod.Post))
{
    <input type="hidden" value="@ViewBag.BookId" name="BookId" />
    <table>
        <tr><td><p>Введите свое имя </p></td>
            <td><input type="text" name="Person" /> </td></tr>
        <tr><td><p>Введите адрес :</p></td>
            <td><input type="text" name="Address" /> </td></tr>
        <tr><td><input type="submit" value="Отправить" /> </td>
                <td></td></tr>
    </table>
}*@

ProcessAuto/Views/Vacancies/ShowCompaniesVacancies.cshtml
@using ProcessAuto.Models.ViewModels
@using System.Collections
@model ProcessAuto.Models.ViewModels.VacancyViewModel

@{
    ViewData["Title"] = "Vacancies";
}
@*<h1>@ViewData["Title"]</h1>

<p>This page will be avaliable for logged user and will let them edit their resume.</p>*@

<h4>@ViewData["Title"]</h4>
@if (User.IsInRole("Company"))
{
    <a class="btn btn-outline-success" asp-area="" asp-controller="Vacancies" asp-action="Create">Create</a>
    <hr>
}
@{
    IEnumerable<VacancyViewModel> vacancies = ViewData["Vacancies"] as IEnumerable<VacancyViewModel>; 
}

<div class="list-group">

@foreach (VacancyViewModel vacancy in vacancies)
{
 
  <a href="@vacancy.Id" class="list-group-item list-group-item-action flex-column align-items-start">    
    <p class="mb-1">Company: @vacancy.Company</p>    
    <p class="mb-1">Stack: @vacancy.Stack</p>   
    <p class="mb-1">Position: @vacancy.Position</p>   
    <p class="mb-1">Slots: @vacancy.Slots</p>       
  </a>

}    

</div>

@*<a class="btn btn-outline-danger" asp-area="" asp-controller="Vacancies" asp-action="Edit">Roles</a>*@

@*@using(Html.BeginForm("Buy", "Resume", FormMethod.Post))
{
    <input type="hidden" value="@ViewBag.BookId" name="BookId" />
    <table>
        <tr><td><p>Введите свое имя </p></td>
            <td><input type="text" name="Person" /> </td></tr>
        <tr><td><p>Введите адрес :</p></td>
            <td><input type="text" name="Address" /> </td></tr>
        <tr><td><input type="submit" value="Отправить" /> </td>
                <td></td></tr>
    </table>
}*@

ProcessAuto/Views/Vacancies/ShowSomeVacancy.cshtml
@using ProcessAuto.Models.ViewModels
@using System.Collections
@model ProcessAuto.Models.ViewModels.VacancyViewModel

@{
    ViewData["Title"] = "Vacancy";
}

<h4>@ViewData["Title"]</h4>


@{
    VacancyViewModel vacancy = ViewData["Vacancy"] as VacancyViewModel;
}

<ul class="list-group">
    <span >
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Company
         <span class="badge badge-primary badge-pill">@vacancy.Company</span> 
      </li>
    </span>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Position
    <span class="badge badge-primary badge-pill">@vacancy.Position</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Stack
    <span class="badge badge-primary badge-pill">@vacancy.Stack</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Slots
    <span class="badge badge-primary badge-pill">@vacancy.Slots</span>
  </li>
</ul>

@*<button class="btn btn-light" asp-area="" asp-controller="" asp-action="">Respond</button>*@

@*<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Add to favlurites
</button>*@



<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    @if (User.IsInRole("Student") && User.IsInRole("Admin") == false) {
  <div class="btn-group mr-2" role="group" aria-label="First group">
        @if (ViewData["checkIfAlreadyResponded"].ToString() == "0")
        {
            <a class="btn btn-light" asp-area="" asp-controller="Vacancies" asp-action="RespondOnVacancy" asp-route-vacId="@ViewData["VacancyId"]">Respond</a>
        }
        else
        {            
            <div class="alert alert-warning" role="alert" >Thanks for your respond! We will contact with you soon! </div>
        }
    </div>
    }
    @if (User.IsInRole("Company")) {
  <div class="btn-group mr-2" role="group" aria-label="First group">
    <a class="btn btn-light" asp-area="" asp-controller="Vacancies" asp-action="ShowVacancyResponds" asp-route-vacId="@ViewData["VacancyId"]">Show Responds</a>
  </div>
    }
    @if (User.IsInRole("Compan")) {
  <div class="btn-group mr-2" role="group" aria-label="First group">
    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@ViewBag.Id">Delete</a>
  </div>  
    }
    @if (User.IsInRole("Admino") == false) {
  <div class="btn-group mr-2" role="group" aria-label="Second group">
    <div class="btn-group-toggle" data-toggle="buttons">
  @*<label class="btn btn-outline-warning">
    <input type="checkbox" checked autocomplete="off">
    @*<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Add to favourites*@
  @*</label>*@
</div>
  </div>  
    }
</div>

ProcessAuto/Views/Vacancies/ShowVacancyResponds.cshtml
@using ProcessAuto.Models
@using ProcessAuto.Models.ViewModels
@using System.Collections

@{
    ViewData["Title"] = "Vacancy Responds";
}
@*<h1>@ViewData["Title"]</h1>

<p>This page will be avaliable for logged user and will let them edit their resume.</p>*@

@*<h4>@ViewData["Title"]</h4>*@

@{
    IEnumerable<VacancyRespondViewModel> responds = ViewData["Responds"] as IEnumerable<VacancyRespondViewModel>; 
}

<div id="modDialog" class="modal fade" >
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<div class="list-group">

    <div id="modDialog" class="modal fade" >
        <div id="dialogContent" class="modal-dialog"></div>
    </div>

@foreach (VacancyRespondViewModel r in responds)
{

    <h3>Vacancy of user @r.Email. </h3>    
   
    <p class="mb-1">About Yourself: @r.AboutYourself</p>    
    <p class="mb-1">Stack: @r.Stack</p>   
    <p class="mb-1">Programming Languages: @r.ProgrammingLanguages</p>   
    <p class="mb-1">Hobbies: @r.Hobbies</p>       
    <p class="mb-1">Working Experience: @r.WorkingExperience</p>         
    
    if (r.RespondStage == VacancyStage.Sent)
    {
        <h4>Current stage: Получен отклик от студента</h4>

        <div class="btn-group btn-group-justified">
        <a type="button" class="btn btn-outline-success" asp-controller="VacancyResponds" asp-action="AssignInterview" asp-route-respondId="@r.RespondId" asp-route-vacId="@ViewData["VacId"]">Assign an Interview</a>
        <a type="button" class="btn btn-outline-danger" asp-controller="VacancyResponds" asp-action="SetStatusNoOffer" asp-route-respondId="@r.RespondId" asp-route-vacId="@ViewData["VacId"]">Not interested</a>
        </div>
    }
    if (r.RespondStage == VacancyStage.InterviewAssigned)
    {
         <h4>Current stage: Назначено собеседование. Текущая дата: @r.InterviewDate.ToString("dd.MM.yyyy")</h4>

         <div class="btn-group btn-group-justified">
         <a type="button" class="btn btn-outline-success" asp-controller="VacancyResponds" asp-action="AssignInterview" asp-route-respondId="@r.RespondId" asp-route-vacId="@ViewData["VacId"]">Change interview date</a>         
         <a type="button" class="btn btn-outline-info" asp-controller="VacancyResponds" asp-action="SetStatusOfferSent" asp-route-respondId="@r.RespondId" asp-route-vacId="@ViewData["VacId"]">Send offer</a>         
         <a type="button" class="btn btn-outline-danger" asp-controller="VacancyResponds" asp-action="SetStatusNoOffer" asp-route-respondId="@r.RespondId" asp-route-vacId="@ViewData["VacId"]">No offer</a>
         </div>         
    }
    if (r.RespondStage == VacancyStage.NoOffer)
    {
        <h4>Current stage: Оффера не будет.</h4>
    }
    if (r.RespondStage == VacancyStage.OfferSent)
    {        
        if (r.StudentsVerdict == StudentsVerdict.Awaiting)
        {
            <h4>Current stage: Проведено собеседование. Студент получил оффер. Ожидается вердикт студента.</h4>
            <div>No answer yet</div>
        }
        if (r.StudentsVerdict == StudentsVerdict.Declined)
        {
            <h4>Current stage: Студент отклонил полученный оффер.</h4>
            <div>Offer was DECLINED by student</div> 
        }
        if (r.StudentsVerdict == StudentsVerdict.Accepted) 
        {
            <h4>Current stage: Оффер принят студентом.</h4>
            <div>Offer was accepted by student</div>
        }
    }

    <hr>

}    

@section scripts
{
    <script type="text/javascript">
 
        $(function () {
            $.ajaxSetup({ cache: false });
           $(".respondItem").click(function (e) {
 
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}

</div>